### ISSUE TITLE
Implement metric endpoints 

### ISSUE THREAD

**Issue by garuppel** [clouditor/clouditor#641] opened 2022-04-20 14:56 UTC
- [ ] UpdateMetricConfiguration()
- [ ] GetMetricImplementation()
- [ ] UpdateMetricImplementation()

**Comment by oxisto** [comment] 2022-04-20 15:26
Duplicate of https://github.com/clouditor/clouditor/issues/495?

**Comment by garuppel** [comment] 2022-04-20 15:29
Yes, sorry.

**Comment by garuppel** [comment] 2022-04-20 15:30
Duplicate of #495

**Closed** 2022-04-20 15:29 UTC
